#pragma once

#define KERNEL_CODE_SEGMENT_INDEX 2
#define KERNEL_DATA_SEGMENT_INDEX 3
#define USER_CODE_SEGMENT_INDEX 4
#define USER_DATA_SEGMENT_INDEX 5

#define KERNEL_CODE_SELECTOR (KERNEL_CODE_SEGMENT_INDEX*8)
#define KERNEL_DATA_SELECTOR (KERNEL_DATA_SEGMENT_INDEX*8)
#define USER_CODE_SELECTOR (USER_CODE_SEGMENT_INDEX*8)
#define USER_DATA_SELECTOR (USER_DATA_SEGMENT_INDEX*8)

void mm_init();
