name: qemu

on:
  push:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout the repo with all submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build Busybox
      run: |
        cd 3rdparty/busybox
        make SKIP_STRIP=y

    - name: Build Kernel
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 ..
        make

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}
      
