name: qemu

on:
  push:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Install prerequisites
      run: |
        sudo apt-get install -y ninja-build g++-10
        sudo python3 -m pip install meson

    # Code checkout
    - name: Checkout the repo with all submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # Build mlibc
    - name: Build mlibc
      run: |
        cd 3rdparty/mlibc
        mkdir build_cross
        cd build_cross
        meson -Dstatic=true -Dprefix=$(pwd)/install -Dbuild_tests=true --cross-file ../cross_file.txt ..
        ninja
        ninja install
        # mlibc does not link "ar" but busybox requires it
        ln -s /usr/bin/ar install/bin/mlibc-ar

    # Build busybox
    - name: Build busybox
      run: |
        cd 3rdparty/busybox
        ./generate_config.sh
        make SKIP_STRIP=y

    # Build kernel binary
    - name: Build Kernel
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 ..
        make
